spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springcloud-sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: 106.13.117.203
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15000
  cloud:
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json

mybatis:
  type-aliases-package: com.dmcq.order.domain.entity
  mapper-locations: classpath:mapper/*.xml
  mappers: com.dmcq.order.common.mapper.MyBaseMapper
  not-empty: false
  identity: MYSQL

# server:
#   port: 8103

# logging:
#  path: log
#  file: order.log
#  level: info

swagger:
  enable: true

env:
  dev1

girl:
  name: lily
  age: 18
