spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Dmcq123456!
    url: jdbc:mysql://106.13.117.203:3306/springcloud-sell?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
  redis:
    host: 106.13.117.203
    port: 6379
  rabbitmq:
    host: 106.13.117.203
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15000
  cloud:
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json

mybatis:
  type-aliases-package: com.dmcq.product.domain.entity
  mapper-locations: classpath:mapper/*.xml
  mappers: com.dmcq.product.common.mapper.MyBaseMapper
  not-empty: false
  identity: MYSQL

# logging:
#   path: log
#   file: product.log
#   level: info

swagger:
  enable: true

env:
  dev
